### ISSUE TITLE
browsebysection -> browsebyidentifier

### ISSUE THREAD

**Issue by klausru** [pkp/browseBySection#1]
Dear NateWr

in what way is this plugin different from https://github.com/pkp/ojs/tree/master/plugins/generic/browse ?
As I can see from the browse plugin in the master tree it allows for browsing by section or IdentifyTypes. We are using the feature "browse by IdentifyTypes" in our 2.4.8 Version and it's very useful.
Regards
Klaus

**Comment by NateWr** [comment]
Hi @klausru. I apologize for the very late response. I mistakenly wasn't watching this repo. This plugin is for OJS 3.1+ only. The Browse plugin is for the 2.x versions only.
