### ISSUE TITLE
Did not work on 3.1.1.1

### ISSUE THREAD

**Issue by stefesciberras** [pkp/browseBySection#15]
Tried this on two installations of OJS 3.1.1.1, but when I go to Journal-> Sections -> click on EDIT a section, I get a failed AJAX error.

error log shows:
[09-Jan-2019 16:49:36 Europe/Malta] PHP Fatal error:  Call to a member function getData() on null in ******************ric/browseBySection/BrowseBySectionPlugin.inc.php on line 152

**Comment by NateWr** [comment]
Hi @stefesciberras,

This sounds like there may be an issue with the section data in your database. The error on Line 152 is here:

https://github.com/pkp/browseBySection/blob/master/BrowseBySectionPlugin.inc.php#L152

That means that `$section` is `null`, which means that no section with the requested ID could be retrieved from the database:

```
$section = $sectionDao->getById($sectionForm->getSectionId(), $contextId);
```

I would recommend checking to see what the ID is of the section you're trying to edit, then checking your database to see if a section with that ID exists. It could be that some section info in your database is incorrect or that the request is submitting the wrong ID or something like that.
