### ISSUE TITLE
No branch working with OJS 3.1.2-1

### ISSUE THREAD

**Issue by nils-stefan-weiher** [pkp/browseBySection#17]
Hi @NateWr ,

currently none of the branches of the Plugin work with OJS 3.1.2-1 
Master branch has adaptions for the OJS master branch which wont work with the current release.

Could you open a branch for OJS 3.1.2? 
I think you need all commits including https://github.com/pkp/browseBySection/commit/72ad6b220016dfdcfc310b1b76e942efda11470a from master.

Regards,

Nils Stefan Weiher

**Comment by nils-stefan-weiher** [comment]
I tested the plugin with the code from https://github.com/pkp/browseBySection/commit/72ad6b220016dfdcfc310b1b76e942efda11470a. And it seems to work in 3.1.2-1

**Comment by NateWr** [comment]
Thanks for reporting, @isgrim! I've now created a `stable-3_1_2` branch for the plugin. https://github.com/pkp/browseBySection/tree/stable-3_1_2
