### ISSUE TITLE
OJS 3.3.0.10 Compatibility

### ISSUE THREAD

**Issue by Nostrabramus** [pkp/browseBySection#28]
Hello,

I tried to use this plugin with OJS 3.3.0.10 but this doesn't works.

Can you confirm it for me? 

When do you expect a working version to be released for newer versions of OJS?

Regards

**Comment by ctgraham** [comment]
@Nostrabramus , can you describe the specific misbehavior or error messages you are seeing?

**Comment by Nostrabramus** [comment]
Hello,
after installing the plugin i did not have the expected behavior. In particular, when I go to create a "navigation menu item" I don't find among the "navigation menu type" the items relating to the sections I have previously created.

Regards

**Comment by wopsononock** [comment]
I'm going to take a look at this.

**Comment by Nostrabramus** [comment]
Thank you very much,
I look forward for news.

Regards

**Comment by wopsononock** [comment]
I installed this plugin on a test site, but still can't figure out what it's supposed to do!  It seems like the effect is mainly intended to be user-facing, with some kind of sorting options.  Can you elaborate a little more?  Is there an existing site where this is working and I could try it out?  Please bear with me, I'm filling in for the author.

**Comment by wopsononock** [comment]
Looks like this is in use on https://goethe-lexicon.pitt.edu/GL/section/view/entries With that context, I'm going to install the plugin in a test version of the site and experiment with adding a section/nav like you say.

**Comment by Nostrabramus** [comment]
Hello,
what i couldn't do was create a section menu, like on this website:
https://www.actaitalica.it/
I mean the item "Journal's Section".

But I understood the problem, I forgot to flag the "Section Browsing" option in the sections.

Sorry if I wasted your time, everything works fine.

Thank you,

**Comment by Nostrabramus** [comment]
there was an user configuration error

**Comment by wopsononock** [comment]
Unfortunately I was not able to replicate this problem.  I installed the latest release of browseBySection in a journal running on ojs 3.3.0.10 and was able to see an existing section in the navigation menu type dropdown.  I created a new section and it appeared there as well.
